# SPDX-FileCopyrightText: 2026 Helmholtz-Zentrum Berlin für Materialien und Energie GmbH
# SPDX-License-Identifier: MIT

from __future__ import annotations

import logging
import math
import numbers
import re
from datetime import datetime
from pathlib import Path
from typing import Any, List, Optional, Tuple, cast

import pandas as pd

from .model import ExportBundle, ExportScan
from .writer_base import ExportWriter, register_writer

logger = logging.getLogger(__name__)

_WHITESPACE_RE = re.compile(r"\s+")


class SpecWriter(ExportWriter):
    """    
    SPEC data rows are numeric. 

    * numeric columns are written as-is
    * datetime columns are converted to POSIX seconds     
    * string columns are written only if every non-empty value can be converted to numeric
    * non-numeric columns documented in ``#C`` lines
    * include_non_numeric=True`` to enable string tokens in data rows.
    """

    name = "spec"
    extension = ".dat"

    def __init__(
        self,
        *,
        include_metadata_comments: bool = True,
        include_metadata_monitor: bool = False,
        include_non_numeric: bool = False,
        precision: int = 12,
    ) -> None:
        self.include_metadata_comments = bool(include_metadata_comments)
        self.include_metadata_monitor = bool(include_metadata_monitor)
        self.include_non_numeric = bool(include_non_numeric)
        self.precision = int(precision)
        logger.debug(
            "Initialized SpecWriter metadata_comments=%s metadata_monitor=%s non_numeric=%s precision=%d",
            self.include_metadata_comments, self.include_metadata_monitor,
            self.include_non_numeric, self.precision,
        )
        # raise RuntimeError("intentional crash") # test handling

    def write(self, bundle: ExportBundle, output_file: Path) -> Path:
        bundle.require_scans()
        output_path = Path(output_file).expanduser()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        logger.debug("Writing SPEC output=%s scans=%d", output_path, len(bundle.scans))

        now = datetime.now().astimezone()
        with output_path.open("w", encoding="utf-8") as handle:
            self._write_file_header(handle, output_path, bundle, now)
            for scan_no, scan in enumerate(bundle.scans, start=1):
                self._write_scan_block(handle, scan_no, scan, now)

        logger.debug("Finished SPEC output=%s size_bytes=%d", output_path, output_path.stat().st_size)
        return output_path

    # ----------------------------------------------------   Header ---------------------------------------------
    #
    # Lines beginning with '#' are metadata/control records.
    # Data rows follow after the #L line.
    #
    #   #F  File name
    #   #E  File creation time as Unix epoch (seconds since 1970)
    #   #D  Human-readable date/time
    #   #C  Free-form comment or metadata
    #   #S  Start of a scan ("scan number" + scan description)
    #   #N  Number of data columns in the scan
    #   #L  Column labels corresponding to each value in the data rows
    #
    #######  There are more items but skipped for now TODO: check for useful meta data@kiwi 
    #   #On     Full motor names.
    #   #on     Short motor names (mnemonics).
    #   #Pn     Motor positions at scan start.
    #  
    #   #Jn     Full counter names.
    #   #jn     Short counter names.
    #  
    #   #T      Counting time per point.
    #   #M      Monitor counts per point.
    #   #I      Data normalization factor.
    #  
    #   #Gn     Diffractometer geometry parameters.
    #   #Q      Reciprocal-space coordinates (H, K, L).
    #  
    #   #R      User-defined scan results.
    #   #U      User-defined information.
    #   #X      Temperature or site-specific value.
    #  
    #   #@MCA   MCA detector definition.
    #   #MCA    MCA spectrum reference or inline data.
    #   #@CALIB MCA calibration coefficients.
    #   #@CHANN MCA channel configuration.
    #   #@CTIME MCA counting times.
    #   #@ROI   MCA region of interest.
    #  
    #   #@IMG   Image detector definition.
    #   #IMG    Image reference or inline image data.
    #   @       Inline array data (MCA/image values).

    def _write_file_header(self, handle, output_path: Path, bundle: ExportBundle, now: datetime) -> None:
        logger.debug("Writing SPEC file header output=%s manifest=%s manifest_header_keys=%s",
            output_path, bundle.manifest_file, sorted(bundle.manifest_header.keys()))

        handle.write(f"#F {output_path}\n")
        handle.write(f"#E {int(now.timestamp())}\n")
        handle.write(f"#D {self._spec_date(now)}\n")
        handle.write("#C Generated by kiwi-scan (https://github.com/hz-b/kiwi-scan)\n")
        if bundle.manifest_file is not None:
            handle.write(f"#C Source manifest: {self._comment(bundle.manifest_file)}\n")
        if bundle.manifest_header:
            created_at = bundle.manifest_header.get("created_at")
            version = bundle.manifest_header.get("kiwi_scan_version")
            if created_at:
                handle.write(f"#C Manifest created_at: {self._comment(created_at)}\n")
            if version:
                handle.write(f"#C kiwi_scan_version: {self._comment(version)}\n")
            else:
                handle.write("#C kiwi_scan_version: 0.0.0\n")

        handle.write("\n")

    def _write_scan_block(self, handle, scan_no: int, scan: ExportScan, fallback_date: datetime) -> None:
        logger.debug(
            "Preparing SPEC scan block number=%d label=%s rows=%d source_columns=%d",
            scan_no, scan.label, len(scan.data), len(scan.data.columns),
        )
        labels, table, dropped = self._prepare_table(scan.data)
        # spec is writing the file after the scan, kiwi scan creates the file including date time stamp at the beginning of the scan
        scan_date = scan.created_at or self._file_time(scan.data_file) or fallback_date
        command = f"{scan.scan_type or 'kiwi_scan'} {scan.label}"
        
        handle.write(f"#S {scan_no} {self._comment(command)}\n")
        handle.write(f"#D {self._spec_date(scan_date)}\n")
        if scan.scan_id:
            handle.write(f"#C kiwi_scan_id: {self._comment(scan.scan_id)}\n")
        if scan.scan_type:
            handle.write(f"#C kiwi_scan_type: {self._comment(scan.scan_type)}\n")
        if scan.data_file is not None:
            handle.write(f"#C data_file: {self._comment(scan.data_file)}\n")
        if scan.metadata_file is not None:
            handle.write(f"#C metadata_file: {self._comment(scan.metadata_file)}\n")

        if self.include_metadata_comments and scan.metadata is not None:
            self._write_metadata_comments(handle, scan.metadata)

        if dropped:
            dropped_columns = ", ".join(self._comment(x) for x in dropped)
            handle.write(f"#C kiwi_spec_dropped_columns: {dropped_columns}\n")

        handle.write(f"#N {len(labels)}\n")
        label_line = "  ".join(labels)
        handle.write(f"#L {label_line}\n")
        
        for row in table.itertuples(index=False, name=None):
            handle.write(" ".join(self._format_value(value) for value in row) + "\n")
        handle.write("\n")
        logger.debug(
            "Wrote SPEC scan block number=%d output_columns=%d rows=%d dropped_columns=%s",
            scan_no, len(labels), len(table), dropped,
        )

    def _write_metadata_comments(self, handle, metadata: Any) -> None:
        """ 
        Write metadata constants and optionally monitor events as comments.
        Depending on monitor data this could bloat the file, therefore default behaviour is to skip monitor data.
        TODO: optionally convert (e.g. resample) monitor data to data columns.
        """
        logger.debug(
            "Writing metadata comments constants=%d include_monitor=%s",
            len(metadata.constants), self.include_metadata_monitor,
        )
        for key, value in sorted(metadata.constants.items()):
            handle.write(f"#C metadata_constant {self._label(key)}: {self._comment(value)}\n")

        if not self.include_metadata_monitor:
            return

        df_raw = getattr(metadata, "df_raw", None)
        if df_raw is None or df_raw.empty:
            return

        logger.debug("Writing %d metadata monitor rows as SPEC comments", len(df_raw))
        columns = [str(column) for column in df_raw.columns]
        for row in df_raw.itertuples(index=False, name=None):
            fields = []
            for column, value in zip(columns, row):
                if self._is_missing_metadata_value(value):
                    continue
                fields.append(f"{self._label(column)}={self._metadata_comment_value(value)}")

            if fields:
                metadata_fields = " ".join(fields)
                handle.write(f"#C metadata_monitor {metadata_fields}\n")

    @classmethod
    def _metadata_comment_value(cls, value: Any) -> str:
        """ Format one metadata value without comment line breaks. """
        if isinstance(value, (datetime, pd.Timestamp)):
            return cls._comment(value.isoformat())
        return cls._comment(value)

    @staticmethod
    def _is_missing_metadata_value(value: Any) -> bool:
        """ Return True for scalar pandas missing values, no arrays. """
        if value is None:
            return True

        if not pd.api.types.is_scalar(value):
            return False

        return bool(pd.isna(value))

    # ------------------------------------------- Data ----------------------------------------------

    def _prepare_table(self, df: pd.DataFrame) -> Tuple[List[str], pd.DataFrame, List[str]]:
        if df is None or df.empty:
            raise ValueError("Cannot write empty scan dataframe to SPEC")

        output_columns = []
        labels = []
        dropped = []

        logger.debug("Preparing SPEC table rows=%d columns=%d", len(df), len(df.columns))
        for index, column in enumerate(df.columns):
            series = df.iloc[:, index]
            converted, label = self._convert_column(str(column), series)
            if converted is None:
                dropped.append(str(column))
                continue
            output_columns.append(converted.reset_index(drop=True))
            labels.append(label)

        if not output_columns:
            raise ValueError("No numeric-compatible columns available for SPEC export")

        labels = self._unique_labels(labels)
        table = pd.concat(output_columns, axis=1)
        table.columns = labels
        logger.debug("Prepared SPEC table output_columns=%d dropped_columns=%s", len(labels), dropped)
        return labels, table, dropped

    def _convert_column(self, name: str, series: pd.Series) -> Tuple[Optional[pd.Series], str]:
        label = self._label(name)

        if self._is_datetime_series(series):
            logger.debug("SPEC column %s dtype=%s converted=datetime_to_epoch", name, series.dtype)
            converted = series.map(self._datetime_to_epoch)
            return converted, self._label(name + "_epoch_s")

        if pd.api.types.is_bool_dtype(series):
            logger.debug("SPEC column %s dtype=%s converted=bool_to_int", name, series.dtype)
            return series.astype(int), label

        if pd.api.types.is_numeric_dtype(series):
            logger.debug("SPEC column %s dtype=%s kept=numeric", name, series.dtype)
            return series, label

        numeric = cast(pd.Series, pd.to_numeric(series, errors="coerce"))
        meaningful = series.notna() & (series.astype(str).str.strip() != "")
        if bool(meaningful.any()) and bool(
            cast(pd.Series, numeric[meaningful]).notna().all()
        ):
            logger.debug("SPEC column %s dtype=%s converted=numeric_text", name, series.dtype)
            return numeric, label

        if self.include_non_numeric:
            logger.debug("SPEC column %s dtype=%s kept=non_numeric_text", name, series.dtype)
            return series.astype(str), label

        logger.debug("SPEC column %s dtype=%s dropped=non_numeric", name, series.dtype)
        return None, label

    @staticmethod
    def _is_datetime_series(series: pd.Series) -> bool:
        return pd.api.types.is_datetime64_any_dtype(series.dtype)

    @staticmethod
    def _datetime_to_epoch(value: Any) -> float:
        if value is None or not pd.api.types.is_scalar(value):
            return float("nan")

        timestamp = pd.to_datetime(value, errors="coerce")
        if pd.isna(timestamp):
            return float("nan")

        return float(timestamp.timestamp())

    # -------------------------------------------- Formatting ----------------------------------------------

    def _format_value(self, value: Any) -> str:
        if value is None:
            return "nan"
        if pd.api.types.is_scalar(value) and pd.isna(value):
            return "nan"

        if isinstance(value, bool):
            return "1" if value else "0"

        if isinstance(value, numbers.Integral):
            return str(int(value))

        if isinstance(value, numbers.Real):
            return self._format_real(float(value))

        return self._format_text(value)

    def _format_real(self, number: float) -> str:
        if math.isnan(number):
            return "nan"
        if math.isinf(number):
            return "inf" if number > 0 else "-inf"
        return f"{number:.{self.precision}g}"

    @staticmethod
    def _format_text(value: Any) -> str:
        text = str(value).strip()
        if not text:
            return "."
        return _WHITESPACE_RE.sub("_", text)

    @staticmethod
    def _comment(value: Any) -> str:
        """ make long string with no line breaks """
        return str(value).replace("\n", " ").replace("\r", " ")

    @staticmethod
    def _label(value: Any) -> str:
        """ make SPEC column label """
        text = str(value).strip() or "col"
        return _WHITESPACE_RE.sub("_", text)

    @staticmethod
    def _unique_labels(labels: List[str]) -> List[str]:
        result = []
        counts = {}
        for label in labels:
            count = counts.get(label, 0) + 1
            counts[label] = count
            if count == 1:
                result.append(label)
            else:
                result.append(f"{label}_{count}")
        return result

    @staticmethod
    def _spec_date(value: datetime) -> str:
        """ Format: 2026-07-09 13:42:18+00:00 """
        return value.astimezone().strftime("%a %b %d %H:%M:%S %Y")

    @staticmethod
    def _file_time(path: Optional[Path]) -> Optional[datetime]:
        """ File modification time """
        if path is None:
            return None
        try:
            return datetime.fromtimestamp(path.stat().st_mtime).astimezone()
        except OSError:
            return None


register_writer(SpecWriter.name, SpecWriter)
